name: CD

# Trigger this workflow only after your tests workflow succeeds
on:
  workflow_run:
    workflows: ["CI"] 
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only run if CI passed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Install semantic-release
        run: |
          npm install --save-dev semantic-release \
            @semantic-release/npm \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator

      - name: Publish to npm
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npx semantic-release
